In [ ]:
pip install h2o

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting h2o
  Downloading h2o-3.40.0.2.tar.gz (177.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 MB 6.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from h2o) (2.27.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.9/dist-packages (from h2o) (0.8.10)
Requirement already satisfied: future in /usr/local/lib/python3.9/dist-packages (from h2o) (0.18.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->h2o) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->h2o) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->h2o) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->h2o) (2022.12.7)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.40.0.2-py2.py3-none-any.whl size=177693439 sha256=6618b4b7055f0aa0a56fe5e2ffa7d3e1f812b396b102f6a07e14822610e16e01
  Stored in directory: /root/.cache/pip/wheels/b2/79/e3/842b81607eb31946ee24898cc9961b101e6486f988a5103967
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.40.0.2

In [ ]:
!pip install xgboost
import xgboost as xg
import h2o
h2o.init()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xgboost in /usr/local/lib/python3.9/dist-packages (1.7.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from xgboost) (1.22.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from xgboost) (1.10.1)
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.18" 2023-01-17; OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1); OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.9/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpz27x7kt2
  JVM stdout: /tmp/tmpz27x7kt2/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpz27x7kt2/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ----------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.40.0.2
H2O_cluster_version_age:    21 days, 21 hours and 29 minutes
H2O_cluster_name:           H2O_from_python_unknownUser_vqo897
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.172 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.16 final
--------------------------  ----------------------------------

In [ ]:
import pandas as pd

In [9]:
from h2o.estimators import H2OGenericEstimator
path = "/content/drive/MyDrive/DRF_model_python_1680266035802_1.zip"
rf_model= h2o.import_mojo(path)

generic Model Build progress: |██████████████████████████████████████████████████| (done) 100%

In [10]:
rf_model.model_performance()

ModelMetricsBinomialGeneric: generic
** Reported on train data. **

MSE: 0.017505605640559002
RMSE: 0.1323087511866052
LogLoss: 0.08028558473349331
Mean Per-Class Error: 0.0509734941958894
AUC: 0.9811273599286645
AUCPR: 0.9580454776260502
Gini: 0.962254719857329

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.19283058598703115
       0       1      Error    Rate
-----  ------  -----  -------  -----------------
0      194055  584    0.003    (584.0/194639.0)
1      2583    23522  0.0989   (2583.0/26105.0)
Total  196638  24106  0.0143   (3167.0/220744.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.192831     0.936926  228
max f2                       0.124288     0.921968  251
max f0point5                 0.339077     0.964727  195
max accuracy                 0.200658     0.985676  226
max precision                0.999989     1         0
max recall                   0.0118797    1         381
max specificity              0.999989     1         0
max absolute_mcc             0.200658     0.929874  226
max min_per_class_accuracy   0.064651     0.943651  291
max mean_per_class_accuracy  0.111011     0.95547   257
max tns                      0.999989     194639    0
max fns                      0.999989     19609     0
max fps                      0.000447754  194639    399
max tps                      0.0118797    26105     381
max tnr                      0.999989     1         0
max fnr                      0.999989     0.751159  0
max fpr                      0.000447754  1         399
max tpr                      0.0118797    1         381

Gains/Lift Table: Avg response rate: 11.83 %, avg score: 11.79 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0274843                   1                  8.456      8.456              1                1           1                           1                   0.232408        0.232408                   745.6     745.6              0.232408
2        0.0301027                   0.999584           8.456      8.456              1                0.999805    1                           0.999983            0.0221414       0.254549                   745.6     745.6              0.254549
3        0.0400011                   0.97882            8.456      8.456              1                0.9917      1                           0.997933            0.0837004       0.338249                   745.6     745.6              0.338249
4        0.0500036                   0.949645           8.456      8.456              1                0.961978    1                           0.990741            0.0845815       0.422831                   745.6     745.6              0.422831
5        0.100003                    0.456835           8.39318    8.42459            0.99257          0.802456    0.996285                    0.896603            0.419651        0.842482                   739.318   742.459            0.842061
6        0.150002                    0.0704989          1.96211    6.2705             0.232038         0.139231    0.741544                    0.644153            0.0981038       0.940586                   96.2112   527.05             0.896618
7        0.200001                    0.0500207          0.242104   4.76343            0.028631         0.0583603   0.56332                     0.497708            0.012105        0.952691                   -75.7896  376.343            0.853641
8        0.299999                    0.0357801          0.137907   3.22161            0.0163088        0.0414786   0.380985                    0.345634            0.0137905       0.966482                   -86.2093  222.161            0.755871
9        0.400002                    0.0296955          0.0869542  2.43793            0.0102831        0.0325084   0.288308                    0.267351            0.00869565      0.975177                   -91.3046  143.793            0.652318
10       0.5                         0.0254608          0.0861919  1.96759            0.010193         0.0274769   0.232686                    0.219377            0.00861904      0.983796                   -91.3808  96.7592            0.548683
11       0.599998                    0.0221245          0.0697197  1.65129            0.00824499       0.0237433   0.19528                     0.186772            0.00697184      0.990768                   -93.028   65.1285            0.44318
12       0.700001                    0.0190307          0.0467331  1.42206            0.00552661       0.0205692   0.168171                    0.163028            0.00467343      0.995441                   -95.3267  42.2057            0.335065
13       0.799999                    0.0158058          0.0317953  1.24828            0.00376008       0.0174439   0.14762                     0.14483             0.00317947      0.998621                   -96.8205  24.8278            0.225261
14       0.899997                    0.0112004          0.0137907  1.11111            0.00163088       0.0137879   0.131399                    0.13027             0.00137905      1                          -98.6209  11.1114            0.113415
15       1                           0                  0          1                  0                0.00688929  0.118259                    0.117932            0               1                          -100      0                  0

In [14]:
train_h2o = h2o.import_file('/content/drive/MyDrive/train_v1.csv')
train_h2o['Anomaly'] = train_h2o['Anomaly'].asfactor()
test_h2o = h2o.import_file('/content/drive/MyDrive/test_v1.csv')
test_h2o['Anomaly'] = test_h2o['Anomaly'].asfactor()
test_h2o = test_h2o.na_omit()
predictors = train_h2o.drop(['Anomaly','Index'], axis=1).columns
response = 'Anomaly'

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [16]:
rf_train_preds = rf_model.predict(train_h2o)

generic prediction progress: |███████████████████████████████████████████████████| (done) 100%

In [17]:
rf_train_preds

  predict        p0          p1
---------  --------  ----------
        0  0.993615  0.00638491
        0  0.992475  0.00752451
        0  0.988148  0.0118519
        0  0.986943  0.0130575
        0  0.981777  0.0182234
        0  0.989095  0.0109048
        0  0.987147  0.0128528
        0  0.986846  0.0131536
        0  0.987116  0.0128838
        0  0.99006   0.00994044
[220744 rows x 3 columns]

In [22]:
probs_h2o = rf_train_probs = h2o.as_list(rf_train_preds)
probs_rf = probs_h2o.drop('predict',axis =1)
probs_rf

              p0        p1
0       0.993615  0.006385
1       0.992475  0.007525
2       0.988148  0.011852
3       0.986943  0.013057
4       0.981777  0.018223
...          ...       ...
220739  0.000000  1.000000
220740  0.000000  1.000000
220741  0.000000  1.000000
220742  0.000000  1.000000
220743  0.000000  1.000000

[220744 rows x 2 columns]

In [24]:
probdf = pd.read_csv('/content/drive/MyDrive/probdf.csv')

In [26]:
probdf['rf_0'] = probs_rf.iloc[:, 0]
probdf['rf_1'] = probs_rf.iloc[:, 1]
probdf

           xgb_0     xgb_1      rf_0      rf_1
0       0.508812  0.491188  0.993615  0.006385
1       0.508503  0.491497  0.992475  0.007525
2       0.508392  0.491608  0.988148  0.011852
3       0.508706  0.491294  0.986943  0.013057
4       0.509292  0.490708  0.981777  0.018223
...          ...       ...       ...       ...
220739  0.475824  0.524176  0.000000  1.000000
220740  0.475824  0.524176  0.000000  1.000000
220741  0.475824  0.524176  0.000000  1.000000
220742  0.475824  0.524176  0.000000  1.000000
220743  0.475824  0.524176  0.000000  1.000000

[220744 rows x 4 columns]

In [27]:
train = pd.read_csv('/content/drive/MyDrive/train_v1.csv')

In [30]:
probdf['Anomaly'] = train.iloc[:, 2]
probdf

           xgb_0     xgb_1      rf_0      rf_1  Anomaly
0       0.508812  0.491188  0.993615  0.006385        0
1       0.508503  0.491497  0.992475  0.007525        0
2       0.508392  0.491608  0.988148  0.011852        0
3       0.508706  0.491294  0.986943  0.013057        0
4       0.509292  0.490708  0.981777  0.018223        0
...          ...       ...       ...       ...      ...
220739  0.475824  0.524176  0.000000  1.000000        1
220740  0.475824  0.524176  0.000000  1.000000        1
220741  0.475824  0.524176  0.000000  1.000000        1
220742  0.475824  0.524176  0.000000  1.000000        1
220743  0.475824  0.524176  0.000000  1.000000        1

[220744 rows x 5 columns]

In [31]:
from sklearn.linear_model import LogisticRegression
X = probdf[['xgb_0', 'xgb_1','rf_0','rf_1']]
Y = probdf['Anomaly']
logreg_model = LogisticRegression()
logreg_model.fit(X, Y)

LogisticRegression()

In [48]:
test_df = pd.read_csv('/content/drive/MyDrive/test_v1.csv')
test_df = test_df.dropna()
features = list(train.columns)
target = 'Anomaly'
features.remove(target)
features.remove('Index')
features

['Station',
 'Lag1',
 'Lag2',
 'Lag5',
 'Lag10',
 'Lag30',
 'Lag50',
 'diff1',
 'diff2',
 'diff5',
 'diff30',
 'diff50',
 'RollingMean_2',
 'RollingSD_2',
 'RollingMean_3',
 'RollingSD_3',
 'RollingMean_4',
 'RollingSD_4',
 'RollingMean_5',
 'RollingSD_5',
 'RollingMean_25',
 'RollingSD_25',
 'RollingMean_35',
 'RollingSD_35',
 'RollingMean_50',
 'RollingSD_50',
 'RollingMean_100',
 'RollingSD_100',
 'RollingMean_200',
 'RollingSD_200',
 'RollingMean_400',
 'RollingSD_400',
 'RollingMean_800',
 'RollingSD_800',
 'meanaddsd',
 'meandiffsd']

In [34]:
h2o_pred = rf_model.predict(test_h2o)

generic prediction progress: |███████████████████████████████████████████████████| (done) 100%

  predict         p0        p1
---------  ---------  --------
        1  0.0416667  0.958333
        1  0          1
        1  0.04       0.96
        1  0.0679452  0.932055
        1  0.0679452  0.932055
        1  0.107399   0.892601
        1  0.107399   0.892601
        1  0.0873989  0.912601
        1  0.0779871  0.922013
        1  0.0779871  0.922013
[424279 rows x 3 columns]

In [49]:
import json
from xgboost import XGBClassifier
xgb_model = XGBClassifier()
xgb_model.load_model('/content/drive/MyDrive/xgb_model.json')
xgb_probs = xgb_model.predict_proba(test_df[features])
xgb_probs

array([[0.475824  , 0.524176  ],
       [0.475824  , 0.524176  ],
       [0.475824  , 0.524176  ],
       ...,
       [0.5235757 , 0.47642428],
       [0.5235757 , 0.47642428],
       [0.5235757 , 0.47642428]], dtype=float32)

In [50]:
test_probdf= pd.DataFrame(xgb_probs, columns=['xgb_0', 'xgb_1'])
test_probdf

           xgb_0     xgb_1
0       0.475824  0.524176
1       0.475824  0.524176
2       0.475824  0.524176
3       0.475824  0.524176
4       0.475824  0.524176
...          ...       ...
424274  0.523576  0.476424
424275  0.523576  0.476424
424276  0.523576  0.476424
424277  0.523576  0.476424
424278  0.523576  0.476424

[424279 rows x 2 columns]

In [41]:
h2o_pred_test = rf_train_probs = h2o.as_list(h2o_pred)
probs_rf_t = h2o_pred_test.drop('predict',axis =1)
probs_rf_t

              p0        p1
0       0.041667  0.958333
1       0.000000  1.000000
2       0.040000  0.960000
3       0.067945  0.932055
4       0.067945  0.932055
...          ...       ...
424274  0.964100  0.035900
424275  0.966118  0.033882
424276  0.963790  0.036210
424277  0.965347  0.034653
424278  0.964833  0.035167

[424279 rows x 2 columns]

In [51]:
test_probdf['rf_0'] = probs_rf_t.iloc[:, 0]
test_probdf['rf_1'] = probs_rf_t.iloc[:, 1]

           xgb_0     xgb_1      rf_0      rf_1
0       0.475824  0.524176  0.041667  0.958333
1       0.475824  0.524176  0.000000  1.000000
2       0.475824  0.524176  0.040000  0.960000
3       0.475824  0.524176  0.067945  0.932055
4       0.475824  0.524176  0.067945  0.932055
...          ...       ...       ...       ...
424274  0.523576  0.476424  0.964100  0.035900
424275  0.523576  0.476424  0.966118  0.033882
424276  0.523576  0.476424  0.963790  0.036210
424277  0.523576  0.476424  0.965347  0.034653
424278  0.523576  0.476424  0.964833  0.035167

[424279 rows x 4 columns]

In [56]:
test_df = test_df.reset_index(drop=True)

In [57]:
test_probdf['Anomaly'] = test_df['Anomaly']
test_probdf

           xgb_0     xgb_1      rf_0      rf_1  Anomaly
0       0.475824  0.524176  0.041667  0.958333        0
1       0.475824  0.524176  0.000000  1.000000        0
2       0.475824  0.524176  0.040000  0.960000        0
3       0.475824  0.524176  0.067945  0.932055        0
4       0.475824  0.524176  0.067945  0.932055        0
...          ...       ...       ...       ...      ...
424274  0.523576  0.476424  0.964100  0.035900        0
424275  0.523576  0.476424  0.966118  0.033882        0
424276  0.523576  0.476424  0.963790  0.036210        0
424277  0.523576  0.476424  0.965347  0.034653        0
424278  0.523576  0.476424  0.964833  0.035167        0

[424279 rows x 5 columns]

In [58]:
X_test = test_probdf[['xgb_0', 'xgb_1','rf_0','rf_1']]
Y_test = test_probdf['Anomaly']
y_pred = logreg_model.predict(X_test)

In [59]:
y_pred

array([1, 1, 1, ..., 0, 0, 0])

In [60]:
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(Y_test, y_pred))

Accuracy: 0.90
              precision    recall  f1-score   support

           0       0.97      0.91      0.94    361455
           1       0.63      0.83      0.71     62824

    accuracy                           0.90    424279
   macro avg       0.80      0.87      0.83    424279
weighted avg       0.92      0.90      0.91    424279

In [64]:
import numpy as np
from sklearn.metrics import f1_score,precision_score, recall_score

def predict_with_threshold(probs, threshold):
    return (probs[:, 1] >= threshold).astype(int)


y_probs = logreg_model.predict_proba(X_test)


thresholds = np.arange(0, 1.05, 0.05)


best_threshold = 0
best_f1 = 0

for threshold in thresholds:
    y_pred = predict_with_threshold(y_probs, threshold)
    f1 = f1_score(Y_test, y_pred)
    

    if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
        precision = precision_score(Y_test, y_pred)
        recall = recall_score(Y_test, y_pred)

print(f"Best threshold: {best_threshold}")
print(f"Best F1-score: {best_f1}")
print(f"precision: {precision}")
print(f"recall: {recall}")

Best threshold: 0.4
Best F1-score: 0.7138676956554059
precision: 0.6202717461510457
recall: 0.8407296574557493